spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6666/menu-manager
    username: menu-manager
    password: "1"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      platform: postgresql
      mode: never # если необходимо включить schema.sql поставить always
      #schema-locations: classpath:schema.sql  # создает таблицы
      #data-locations: classpath:data.sql     # заполняет данными

# JWT Configuration
jwt:
  secret: your-256-bit-secret-key-here-must-be-at-least-32-chars
  expiration: 86400

  # Настройки Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml # основной changelog файл

  server:
    port: 8080
    servlet:
      context-path: /api

  springdoc:
    api-docs:
      path: /v3/api-docs       # Путь к JSON OpenAPI
    swagger-ui:
      path: /swagger-ui.html   # Путь к Swagger UI
      enabled: true

  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
      com.example.demo: TRACE
