# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: menu-manager
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: menu-manager
    ports:
      - "6666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U menu-manager -d menu-manager" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: arslan1211/menu-manager:0.0.2 # 0.0.2 для linux/arm64 / 0.0.1 для windows
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/menu-manager
      SPRING_DATASOURCE_USERNAME: menu-manager
      SPRING_DATASOURCE_PASSWORD: 1
    ports:
      - "8080:8080"

volumes:
  postgres_data: